unpackaged/main/default/objects/Plan_intervention__c/Plan_intervention__c.object-meta.xml
<CustomObject>
    <label>Plan intervention</label>
    <nameField>
        <displayFormat>PI-{00000000}</displayFormat>
        <label>Plan d&apos;intervention</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Plans intervention</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Plan_Intervention_Context__c/Plan_Intervention_Context__c.object-meta.xml
<CustomObject>
    <label>Plan Intervention Context</label>
    <nameField>
        <displayFormat>PIC-{000000000}</displayFormat>
        <label>Plan Intervention Context Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Plan Intervention Contexts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Plan_Intervention_Context__c/fields/Plan_intervention__c.field-meta.xml
<CustomField>
    <fullName>Plan_intervention__c</fullName>
    <label>Plan intervention</label>
    <referenceTo>Plan_intervention__c</referenceTo>
    <relationshipLabel>Plan Intervention Contexts</relationshipLabel>
    <relationshipName>Plan_Intervention_Contexts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Plan_Intervention_Context__c/fields/Work_Order__c.field-meta.xml
<CustomField>
    <fullName>Work_Order__c</fullName>
    <label>Work Order</label>
    <referenceTo>WorkOrder</referenceTo>
    <relationshipLabel>Plan Intervention Contexts</relationshipLabel>
    <relationshipName>Plan_Intervention_Contexts</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/a_Prestation__c.field-meta.xml
<CustomField>
    <fullName>a_Prestation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prestation de planification</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Intervention</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Acte</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>WorkOrder</referenceTo>
    <relationshipLabel>Interventions</relationshipLabel>
    <relationshipName>Interventions</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/a_Type_de_Prestation__c.field-meta.xml
<CustomField>
    <fullName>a_Type_de_Prestation__c</fullName>
    <label>Type de Prestation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>LAMal</fullName>
            </value>
            <value>
                <fullName>Privé</fullName>
            </value>
            <value>
                <fullName>Fondation</fullName>
            </value>
            <value>
                <fullName>LAA (accident)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Acte__c.field-meta.xml
<CustomField>
    <fullName>Acte__c</fullName>
    <label>Acte</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Code_de_facturation__c.field-meta.xml
<CustomField>
    <fullName>Code_de_facturation__c</fullName>
    <label>Code de facturation</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Code_InterRAI__c.field-meta.xml
<CustomField>
    <fullName>Code_InterRAI__c</fullName>
    <label>Code InterRAI</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Code_LaMAL__c.field-meta.xml
<CustomField>
    <fullName>Code_LaMAL__c</fullName>
    <label>Code LaMAL</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Fr_quence_InterRAI__c.field-meta.xml
<CustomField>
    <fullName>Fr_quence_InterRAI__c</fullName>
    <label>Fréquence InterRAI</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Groupe_InterRAI__c.field-meta.xml
<CustomField>
    <fullName>Groupe_InterRAI__c</fullName>
    <label>Groupe InterRAI</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Nb_InterRAI__c.field-meta.xml
<CustomField>
    <fullName>Nb_InterRAI__c</fullName>
    <label>Nb. InterRAI</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Remarque_de_l_inf_r_f__c.field-meta.xml
<CustomField>
    <fullName>Remarque_de_l_inf_r_f__c</fullName>
    <label>Remarque de l&apos;inf. réf.</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Temps__c.field-meta.xml
<CustomField>
    <fullName>Temps__c</fullName>
    <label>Temps</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Temps_InterRAI__c.field-meta.xml
<CustomField>
    <fullName>Temps_InterRAI__c</fullName>
    <inlineHelpText>Tems en minutes</inlineHelpText>
    <label>Temps InterRAI</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/recordTypes/Acte.recordType-meta.xml
<RecordType>
    <fullName>Acte</fullName>
    <active>true</active>
    <label>Acte</label>
</RecordType>

unpackaged/main/default/objects/WorkOrder/recordTypes/Prestation.recordType-meta.xml
<RecordType>
    <fullName>Prestation</fullName>
    <active>true</active>
    <label>Prestation</label>
</RecordType>

unpackaged/main/default/classes/PrestationController.cls
public with sharing class PrestationController {
    
    @AuraEnabled(cacheable=true)
    public static List<WorkOrder> findPrestationByPlanInerventionId(String planInterventionId) {
        List<id> workOrderIds = new List<id>();
        for(Plan_Intervention_Context__c pic : [SELECT Work_Order__c FROM Plan_Intervention_Context__c WHERE  Plan_intervention__c	= :planInterventionId ]){
            workOrderIds.add(pic.Work_Order__c);
        }

        return [SELECT  Id, 
                        WorkOrderNumber,
                        RecordTypeId, 
                        Code_LaMAL__c, 
                        Code_InterRAI__c, 
                        Groupe_InterRAI__c,
                        Status,
                        Priority,
                        Subject,
                        WorkTypeId,
                        Duration,
                        DurationType,
                        a_Type_de_Prestation__c,
                        WorkType.Name
                    FROM WorkOrder 
                    WHERE RecordType.Name = 'Prestation'
                    AND Id in :workOrderIds
                    WITH SECURITY_ENFORCED
                    ORDER BY WorkOrderNumber desc];
    }


    @AuraEnabled(cacheable=true)
    public static List<WorkOrder> findActesByPlanInerventionId(String planInterventionId) {

        List<id> workOrderIds = new List<id>();
        for(Plan_Intervention_Context__c pic : [SELECT Work_Order__c FROM Plan_Intervention_Context__c WHERE  Plan_intervention__c	= :planInterventionId ]){
            workOrderIds.add(pic.Work_Order__c);
        }

        return [SELECT  Id, 
                        WorkOrderNumber,
                        RecordTypeId, 
                        Code_LaMAL__c, 
                        Code_InterRAI__c, 
                        Groupe_InterRAI__c,
                        Status,
                        Priority,
                        Subject,
                        a_Prestation__c,
                        Acte__c,
                        Remarque_de_l_inf_r_f__c,
                        Temps__c,
                        Fr_quence_InterRAI__c,
                        Nb_InterRAI__c,
                        a_Prestation__r.WorkOrderNumber
                    FROM WorkOrder 
                    WHERE RecordType.Name = 'Acte'
                    AND a_Prestation__c in :workOrderIds
                    WITH SECURITY_ENFORCED
                    ORDER BY WorkOrderNumber desc];
    }



    @AuraEnabled(cacheable=true)
    public static List<WorkOrder> findActesByPrestationId(String prestationId) {

        return [SELECT  Id, 
                        WorkOrderNumber,
                        RecordTypeId, 
                        Code_LaMAL__c, 
                        Code_InterRAI__c, 
                        Groupe_InterRAI__c,
                        Status,
                        Priority,
                        Subject,
                        a_Prestation__c,
                        Temps__c,
                        Remarque_de_l_inf_r_f__c,
                        Acte__c,
                        a_Prestation__r.WorkOrderNumber
                    FROM WorkOrder 
                    WHERE RecordType.Name = 'Acte'
                    AND a_Prestation__c =: prestationId
                    WITH SECURITY_ENFORCED
                    ORDER BY WorkOrderNumber desc];
    }
    

    @AuraEnabled(cacheable=true)
    public static List<WorkOrder> retrieveInterRaiCatalogue() {

        return [SELECT  Id, 
                        WorkOrderNumber,
                        Code_LaMAL__c, 
                        Code_InterRAI__c, 
                        Groupe_InterRAI__c,
                        Status,
                        Priority,
                        Subject,
                        Code_de_facturation__c,
                        Temps__c,
                        Nb_InterRAI__c,
                        Fr_quence_InterRAI__c,
                        Temps_InterRAI__c,
                        WorkTypeId,
                        a_Prestation__r.WorkOrderNumber
                    FROM WorkOrder 
                    WHERE RecordType.Name = 'Catalogue des prestations'
                    WITH SECURITY_ENFORCED
                    ORDER BY Code_InterRAI__c asc];
    }


}