unpackaged/main/default/objects/WorkOrder/fields/a_Derniere_fois_planifie_le__c.field-meta.xml
<CustomField>
    <fullName>a_Derniere_fois_planifie_le__c</fullName>
    <label>Dernière fois planifié le</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/a_Prochaine_planification_le__c.field-meta.xml
<CustomField>
    <fullName>a_Prochaine_planification_le__c</fullName>
    <label>Prochaine planification le</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/recordTypes/Intervention.recordType-meta.xml
<RecordType>
    <fullName>Intervention</fullName>
    <active>true</active>
    <label>Intervention</label>
</RecordType>

unpackaged/main/default/classes/ARC_MassPurge.cls
public class ARC_MassPurge {
    
    @InvocableMethod
    public static void resetInterventions(){
        
        Id recType = [Select Id from RecordType where DeveloperName = 'Intervention'].Id;
        List<WorkOrder> woList = [Select Id, RecordTypeId, Status from WorkOrder where /*Status = 'In Progress' and */RecordTypeId <> :recType ];
    	for(WorkOrder wo :woList){
        	wo.a_Derniere_fois_planifie_le__c = NULL;
            wo.a_Prochaine_planification_le__c = NULL;
        }
        update woList;
        List<WorkOrder> woDel = [Select Id, RecordTypeId, Status from WorkOrder where RecordTypeId = :recType ];
        delete woDel;
    }
}