unpackaged/main/default/objects/Dossier_de_soins__c/Dossier_de_soins__c.object-meta.xml
<CustomObject>
    <label>Dossier de soins</label>
    <nameField>
        <displayFormat>DS-{00000000}</displayFormat>
        <label>Dossier de soins Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dossiers de soins</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/m_dicament__c/m_dicament__c.object-meta.xml
<CustomObject>
    <label>médicament</label>
    <nameField>
        <displayFormat>LM-{00000000}</displayFormat>
        <label>Nom de Liste de médicaments</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>médicaments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/m_dicament__c/fields/Cat_gories__c.field-meta.xml
<CustomField>
    <fullName>Cat_gories__c</fullName>
    <label>Catégories</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Per os</fullName>
            </value>
            <value>
                <fullName>Parentéral</fullName>
            </value>
            <value>
                <fullName>Autre</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/m_dicament__c/fields/Date_de_d_but__c.field-meta.xml
<CustomField>
    <fullName>Date_de_d_but__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <label>Date de début</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/m_dicament__c/fields/Date_de_fin__c.field-meta.xml
<CustomField>
    <fullName>Date_de_fin__c</fullName>
    <label>Date de fin</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/m_dicament__c/fields/Dimanche_check__c.field-meta.xml
<CustomField>
    <fullName>Dimanche_check__c</fullName>
    <formula>IF( INCLUDES ( Jours__c , &apos;Dimanche&apos; ), true, false)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>dim.</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/m_dicament__c/fields/Dossier_de_soins__c.field-meta.xml
<CustomField>
    <fullName>Dossier_de_soins__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dossier de soins</label>
    <referenceTo>Dossier_de_soins__c</referenceTo>
    <relationshipName>Listes_de_m_dicaments</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/m_dicament__c/fields/Jeudi_check__c.field-meta.xml
<CustomField>
    <fullName>Jeudi_check__c</fullName>
    <formula>IF( INCLUDES ( Jours__c , &apos;Jeudi&apos; ), true, false)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>jeu.</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/m_dicament__c/fields/Jours__c.field-meta.xml
<CustomField>
    <fullName>Jours__c</fullName>
    <label>Jours</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Lundi</fullName>
            </value>
            <value>
                <fullName>Mardi</fullName>
            </value>
            <value>
                <fullName>Mercredi</fullName>
            </value>
            <value>
                <fullName>Jeudi</fullName>
            </value>
            <value>
                <fullName>Vendredi</fullName>
            </value>
            <value>
                <fullName>Samedi</fullName>
            </value>
            <value>
                <fullName>Dimanche</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/m_dicament__c/fields/Lundi_check__c.field-meta.xml
<CustomField>
    <fullName>Lundi_check__c</fullName>
    <formula>IF( INCLUDES ( Jours__c , &apos;Lundi&apos; ), true, false)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>lun.</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/m_dicament__c/fields/M_dicament__c.field-meta.xml
<CustomField>
    <fullName>M_dicament__c</fullName>
    <label>Médicament</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/m_dicament__c/fields/Mardi_check__c.field-meta.xml
<CustomField>
    <fullName>Mardi_check__c</fullName>
    <formula>IF( INCLUDES ( Jours__c , &apos;Mardi&apos; ), true, false)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>mar.</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/m_dicament__c/fields/Matin__c.field-meta.xml
<CustomField>
    <fullName>Matin__c</fullName>
    <label>Matin</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/m_dicament__c/fields/Mercredi_check__c.field-meta.xml
<CustomField>
    <fullName>Mercredi_check__c</fullName>
    <formula>IF( INCLUDES ( Jours__c , &apos;Mercredi&apos; ), true, false)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>mer.</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/m_dicament__c/fields/Midi__c.field-meta.xml
<CustomField>
    <fullName>Midi__c</fullName>
    <label>Midi</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/m_dicament__c/fields/Nuit__c.field-meta.xml
<CustomField>
    <fullName>Nuit__c</fullName>
    <label>Nuit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/m_dicament__c/fields/Prise_hebdomadaire__c.field-meta.xml
<CustomField>
    <fullName>Prise_hebdomadaire__c</fullName>
    <formula>IF( INCLUDES ( Jours__c , &apos;Lundi&apos; ), &apos;Lundi&apos;, &apos;&apos;) &amp; &apos;  &apos; &amp;
IF( INCLUDES ( Jours__c , &apos;Mardi&apos; ), &apos;Mardi&apos;, &apos;&apos;) &amp; &apos;  &apos; &amp;
IF( INCLUDES ( Jours__c , &apos;Mercredi&apos; ), &apos;Mercredi&apos;, &apos;&apos;)  &amp; &apos;  &apos; &amp;
IF( INCLUDES ( Jours__c , &apos;Jeudi&apos; ), &apos;Jeudi&apos;, &apos;&apos;)  &amp; &apos;  &apos; &amp;
IF( INCLUDES ( Jours__c , &apos;Vendredi&apos; ), &apos;Vendredi&apos;, &apos;&apos;)  &amp; &apos;  &apos; &amp;
IF( INCLUDES ( Jours__c , &apos;Samedi&apos; ), &apos;Samedi&apos;, &apos;&apos;)  &amp; &apos;  &apos; &amp;
IF( INCLUDES ( Jours__c , &apos;Dimanche&apos; ), &apos;Dimanche&apos;, &apos;&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Prise hebdomadaire</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/m_dicament__c/fields/prise_journaliere__c.field-meta.xml
<CustomField>
    <fullName>prise_journaliere__c</fullName>
    <formula>IF( Matin__c == 0, &apos;&apos;, &apos;MATIN: &apos;&amp; TEXT(Matin__c) &amp;&apos; &apos;&amp; TEXT(Unit__c)  &amp; &apos; sous forme: &apos; &amp; TEXT(Forme_gal_nique__c )&amp; BR() )

&amp;IF( Midi__c == 0, &apos;&apos;, &apos;MIDI: &apos;&amp; TEXT(Midi__c) &amp;&apos; &apos;&amp; TEXT(Unit__c)  &amp; &apos; sous forme: &apos; &amp; TEXT(Forme_gal_nique__c )&amp; BR() )

&amp;IF( Soir__c == 0, &apos;&apos;, &apos;SOIR: &apos;&amp; TEXT(Soir__c) &amp;&apos; &apos;&amp; TEXT(Unit__c)  &amp; &apos; sous forme: &apos; &amp; TEXT(Forme_gal_nique__c )&amp; BR() )

&amp;IF( Nuit__c == 0, &apos;&apos;, &apos;NUIT: &apos;&amp; TEXT(Nuit__c) &amp;&apos; &apos;&amp; TEXT(Unit__c)  &amp; &apos; sous forme: &apos; &amp; TEXT(Forme_gal_nique__c )&amp; BR() )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Prise journalière</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/m_dicament__c/fields/R_serve__c.field-meta.xml
<CustomField>
    <fullName>R_serve__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Réserve</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/m_dicament__c/fields/Samedi_check__c.field-meta.xml
<CustomField>
    <fullName>Samedi_check__c</fullName>
    <formula>IF( INCLUDES ( Jours__c , &apos;Samedi&apos; ), true, false)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>sam.</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/m_dicament__c/fields/Soir__c.field-meta.xml
<CustomField>
    <fullName>Soir__c</fullName>
    <label>Soir</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/m_dicament__c/fields/Vendredi_check__c.field-meta.xml
<CustomField>
    <fullName>Vendredi_check__c</fullName>
    <formula>IF( INCLUDES ( Jours__c , &apos;Vendredi&apos; ), true, false)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>vend.</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Transmission__c/Transmission__c.object-meta.xml
<CustomObject>
    <label>Transmission</label>
    <nameField>
        <displayFormat>T-{00000000}</displayFormat>
        <label>Transmission</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transmissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Transmission__c/fields/Cible__c.field-meta.xml
<CustomField>
    <fullName>Cible__c</fullName>
    <label>Cible</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>état général</fullName>
                <default>true</default>
                <label>état général</label>
            </value>
            <value>
                <fullName>cardio-respiratoire</fullName>
            </value>
            <value>
                <fullName>urinaire</fullName>
            </value>
            <value>
                <fullName>digestif</fullName>
            </value>
            <value>
                <fullName>génital</fullName>
            </value>
            <value>
                <fullName>escarre</fullName>
            </value>
            <value>
                <fullName>cutanéo-muqueux</fullName>
            </value>
            <value>
                <fullName>psychologique</fullName>
            </value>
            <value>
                <fullName>neurologique</fullName>
            </value>
            <value>
                <fullName>douleur</fullName>
            </value>
            <value>
                <fullName>locomoteur</fullName>
            </value>
            <value>
                <fullName>famille</fullName>
            </value>
            <value>
                <fullName>intervenants</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Transmission__c/fields/Date_de_la_transmission__c.field-meta.xml
<CustomField>
    <fullName>Date_de_la_transmission__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <label>Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Transmission__c/fields/Dossier_de_soins_del__c.field-meta.xml
<CustomField>
    <fullName>Dossier_de_soins_del__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dossier de soins</label>
    <referenceTo>Dossier_de_soins__c</referenceTo>
    <relationshipLabel>Transmissions</relationshipLabel>
    <relationshipName>Transmissions_del</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Transmission__c/fields/Evaluations__c.field-meta.xml
<CustomField>
    <fullName>Evaluations__c</fullName>
    <label>Action</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Transmission__c/fields/Indicateur__c.field-meta.xml
<CustomField>
    <fullName>Indicateur__c</fullName>
    <label>Indicateur</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Stable</fullName>
            </value>
            <value>
                <fullName>À surveiller</fullName>
            </value>
            <value>
                <fullName>Instable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Transmission__c/fields/Transmission__c.field-meta.xml
<CustomField>
    <fullName>Transmission__c</fullName>
    <label>Observation</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/classes/DossierSoinController.cls
public with sharing class DossierSoinController {
    
    @AuraEnabled(cacheable=true)
    public static List<Transmission__c> findTransmissionsByDossierSoinId(String dossierSoinId){
        return [SELECT id, 
                        Date_de_la_transmission__c, 
                        Evaluations__c, 
                        Transmission__c, 
                        CreatedById, 
                        Cible__c, 
                        Name,
                        Indicateur__c
                FROM Transmission__c 
                WHERE Dossier_de_soins_del__c =: dossierSoinId 
                ORDER BY Date_de_la_transmission__c desc];
    }

    @AuraEnabled(cacheable=true)
    public static List<m_dicament__c> findMedicamentsByDossierSoinId(String dossierSoinId){
        return [SELECT  id,
                        Dossier_de_soins__c, 
                        Name,
                        Date_de_d_but__c,
                        Date_de_fin__c, 
                        CreatedById,
                        Cat_gories__c,
                        M_dicament__c,
                        prise_journaliere__c,
                        Prise_hebdomadaire__c,
                        Jours__c,
                        Lundi_check__c,
                        Mardi_check__c,
                        Mercredi_check__c,
                        jeudi_check__c,
                        Vendredi_check__c,
                        Samedi_check__c,
                        Dimanche_check__c,
                        R_serve__c,
                        Remarque__c,
                        Matin__c,
                        Midi__c,
                        Soir__c	,
                        Nuit__c
                FROM m_dicament__c 
                WHERE Dossier_de_soins__c =: dossierSoinId 
                ORDER BY Date_de_d_but__c desc];
    }

}